// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(chatterboxFFI)
import chatterboxFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_chatterbox_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_chatterbox_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureChatterboxInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Entry point for the iOS app.
 *
 * Construct once, call `connect()`, then drive `nextEvent()` in a Swift Task.
 */
public protocol ChatterboxClientProtocol: AnyObject, Sendable {
    
    /**
     * Connect and authenticate. Initialises OMEMO. Throws on failure.
     */
    func connect(server: String, username: String, password: String) async throws 
    
    /**
     * Delete all stored messages for a conversation partner.
     */
    func deleteConversation(jid: String) async throws 
    
    /**
     * Gracefully disconnect and close the event stream.
     */
    func disconnect() async 
    
    /**
     * Mark an OMEMO device as untrusted.
     */
    func distrustDevice(jid: String, deviceId: UInt32) async throws 
    
    /**
     * Fetch server-side message archive (MAM, XEP-0313) for `jid` and store
     * any messages newer than `since_unix_secs`.  Returns the new messages
     * oldest-first so the caller can append them to local history.
     */
    func fetchMam(jid: String, sinceUnixSecs: Int64) async throws  -> [FfiMessage]
    
    /**
     * Fetch the roster (contact list) from the server.
     */
    func getContacts() async throws  -> [FfiContact]
    
    /**
     * Fetch OMEMO fingerprints for every known device of `jid`.
     *
     * Returns an empty list if OMEMO is not yet initialised or the contact
     * has no known devices.
     */
    func getFingerprints(jid: String) async throws  -> [FfiFingerprint]
    
    /**
     * Return all contact JIDs that have stored message history, newest-first.
     * Call this after `connect()` to restore previous conversations.
     */
    func listConversations() async throws  -> [String]
    
    /**
     * Load the most recent `limit` messages for a conversation partner.
     * Returns oldest-first so the UI can append them in order.
     */
    func loadHistory(jid: String, limit: UInt32) async throws  -> [FfiMessage]
    
    /**
     * Wait for the next event (message, presence update, or disconnect).
     *
     * Returns `None` only after `disconnect()` is called and the channel drains.
     * Drive this in a Swift Task:
     *
     * ```swift
     * Task {
     * while let event = await client.nextEvent() {
     * switch event { ... }
     * }
     * }
     * ```
     */
    func nextEvent() async  -> FfiEvent?
    
    /**
     * Send an OMEMO-encrypted (or plaintext-fallback) message to `to_jid`.
     * Returns the stored `FfiMessage` so the caller can display it immediately.
     */
    func sendMessage(toJid: String, body: String) async throws  -> FfiMessage
    
    /**
     * Send an XEP-0085 chat state: `is_typing = true` → Composing, false → Paused.
     */
    func sendTyping(jid: String, isTyping: Bool) async throws 
    
    /**
     * Mark an OMEMO device as trusted.
     */
    func trustDevice(jid: String, deviceId: UInt32) async throws 
    
}
/**
 * Entry point for the iOS app.
 *
 * Construct once, call `connect()`, then drive `nextEvent()` in a Swift Task.
 */
open class ChatterboxClient: ChatterboxClientProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_chatterbox_fn_clone_chatterboxclient(self.pointer, $0) }
    }
    /**
     * Create a new (disconnected) client.
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_chatterbox_fn_constructor_chatterboxclient_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_chatterbox_fn_free_chatterboxclient(pointer, $0) }
    }

    

    
    /**
     * Connect and authenticate. Initialises OMEMO. Throws on failure.
     */
open func connect(server: String, username: String, password: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_connect(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(server),FfiConverterString.lower(username),FfiConverterString.lower(password)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_void,
            completeFunc: ffi_chatterbox_rust_future_complete_void,
            freeFunc: ffi_chatterbox_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Delete all stored messages for a conversation partner.
     */
open func deleteConversation(jid: String)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_delete_conversation(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(jid)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_void,
            completeFunc: ffi_chatterbox_rust_future_complete_void,
            freeFunc: ffi_chatterbox_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Gracefully disconnect and close the event stream.
     */
open func disconnect()async   {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_disconnect(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_void,
            completeFunc: ffi_chatterbox_rust_future_complete_void,
            freeFunc: ffi_chatterbox_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: nil
            
        )
}
    
    /**
     * Mark an OMEMO device as untrusted.
     */
open func distrustDevice(jid: String, deviceId: UInt32)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_distrust_device(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(jid),FfiConverterUInt32.lower(deviceId)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_void,
            completeFunc: ffi_chatterbox_rust_future_complete_void,
            freeFunc: ffi_chatterbox_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Fetch server-side message archive (MAM, XEP-0313) for `jid` and store
     * any messages newer than `since_unix_secs`.  Returns the new messages
     * oldest-first so the caller can append them to local history.
     */
open func fetchMam(jid: String, sinceUnixSecs: Int64)async throws  -> [FfiMessage]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_fetch_mam(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(jid),FfiConverterInt64.lower(sinceUnixSecs)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_rust_buffer,
            completeFunc: ffi_chatterbox_rust_future_complete_rust_buffer,
            freeFunc: ffi_chatterbox_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiMessage.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Fetch the roster (contact list) from the server.
     */
open func getContacts()async throws  -> [FfiContact]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_get_contacts(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_rust_buffer,
            completeFunc: ffi_chatterbox_rust_future_complete_rust_buffer,
            freeFunc: ffi_chatterbox_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiContact.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Fetch OMEMO fingerprints for every known device of `jid`.
     *
     * Returns an empty list if OMEMO is not yet initialised or the contact
     * has no known devices.
     */
open func getFingerprints(jid: String)async throws  -> [FfiFingerprint]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_get_fingerprints(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(jid)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_rust_buffer,
            completeFunc: ffi_chatterbox_rust_future_complete_rust_buffer,
            freeFunc: ffi_chatterbox_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiFingerprint.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Return all contact JIDs that have stored message history, newest-first.
     * Call this after `connect()` to restore previous conversations.
     */
open func listConversations()async throws  -> [String]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_list_conversations(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_rust_buffer,
            completeFunc: ffi_chatterbox_rust_future_complete_rust_buffer,
            freeFunc: ffi_chatterbox_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceString.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Load the most recent `limit` messages for a conversation partner.
     * Returns oldest-first so the UI can append them in order.
     */
open func loadHistory(jid: String, limit: UInt32)async throws  -> [FfiMessage]  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_load_history(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(jid),FfiConverterUInt32.lower(limit)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_rust_buffer,
            completeFunc: ffi_chatterbox_rust_future_complete_rust_buffer,
            freeFunc: ffi_chatterbox_rust_future_free_rust_buffer,
            liftFunc: FfiConverterSequenceTypeFfiMessage.lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Wait for the next event (message, presence update, or disconnect).
     *
     * Returns `None` only after `disconnect()` is called and the channel drains.
     * Drive this in a Swift Task:
     *
     * ```swift
     * Task {
     * while let event = await client.nextEvent() {
     * switch event { ... }
     * }
     * }
     * ```
     */
open func nextEvent()async  -> FfiEvent?  {
    return
        try!  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_next_event(
                    self.uniffiClonePointer()
                    
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_rust_buffer,
            completeFunc: ffi_chatterbox_rust_future_complete_rust_buffer,
            freeFunc: ffi_chatterbox_rust_future_free_rust_buffer,
            liftFunc: FfiConverterOptionTypeFfiEvent.lift,
            errorHandler: nil
            
        )
}
    
    /**
     * Send an OMEMO-encrypted (or plaintext-fallback) message to `to_jid`.
     * Returns the stored `FfiMessage` so the caller can display it immediately.
     */
open func sendMessage(toJid: String, body: String)async throws  -> FfiMessage  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_send_message(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(toJid),FfiConverterString.lower(body)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_rust_buffer,
            completeFunc: ffi_chatterbox_rust_future_complete_rust_buffer,
            freeFunc: ffi_chatterbox_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFfiMessage_lift,
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Send an XEP-0085 chat state: `is_typing = true` → Composing, false → Paused.
     */
open func sendTyping(jid: String, isTyping: Bool)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_send_typing(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(jid),FfiConverterBool.lower(isTyping)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_void,
            completeFunc: ffi_chatterbox_rust_future_complete_void,
            freeFunc: ffi_chatterbox_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    
    /**
     * Mark an OMEMO device as trusted.
     */
open func trustDevice(jid: String, deviceId: UInt32)async throws   {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_chatterbox_fn_method_chatterboxclient_trust_device(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(jid),FfiConverterUInt32.lower(deviceId)
                )
            },
            pollFunc: ffi_chatterbox_rust_future_poll_void,
            completeFunc: ffi_chatterbox_rust_future_complete_void,
            freeFunc: ffi_chatterbox_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError_lift
        )
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeChatterboxClient: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ChatterboxClient

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ChatterboxClient {
        return ChatterboxClient(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ChatterboxClient) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ChatterboxClient {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ChatterboxClient, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatterboxClient_lift(_ pointer: UnsafeMutableRawPointer) throws -> ChatterboxClient {
    return try FfiConverterTypeChatterboxClient.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeChatterboxClient_lower(_ value: ChatterboxClient) -> UnsafeMutableRawPointer {
    return FfiConverterTypeChatterboxClient.lower(value)
}




/**
 * A contact as seen by the iOS UI.
 */
public struct FfiContact {
    public var jid: String
    public var displayName: String
    /**
     * "online" | "offline" | "away"
     */
    public var status: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(jid: String, displayName: String, 
        /**
         * "online" | "offline" | "away"
         */status: String) {
        self.jid = jid
        self.displayName = displayName
        self.status = status
    }
}

#if compiler(>=6)
extension FfiContact: Sendable {}
#endif


extension FfiContact: Equatable, Hashable {
    public static func ==(lhs: FfiContact, rhs: FfiContact) -> Bool {
        if lhs.jid != rhs.jid {
            return false
        }
        if lhs.displayName != rhs.displayName {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(jid)
        hasher.combine(displayName)
        hasher.combine(status)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiContact: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiContact {
        return
            try FfiContact(
                jid: FfiConverterString.read(from: &buf), 
                displayName: FfiConverterString.read(from: &buf), 
                status: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiContact, into buf: inout [UInt8]) {
        FfiConverterString.write(value.jid, into: &buf)
        FfiConverterString.write(value.displayName, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiContact_lift(_ buf: RustBuffer) throws -> FfiContact {
    return try FfiConverterTypeFfiContact.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiContact_lower(_ value: FfiContact) -> RustBuffer {
    return FfiConverterTypeFfiContact.lower(value)
}


/**
 * An OMEMO device fingerprint as seen by the iOS UI.
 */
public struct FfiFingerprint {
    public var deviceId: UInt32
    /**
     * 64-char hex string, space-grouped for display: "AABB CCDD …"
     */
    public var fingerprint: String
    public var isTrusted: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(deviceId: UInt32, 
        /**
         * 64-char hex string, space-grouped for display: "AABB CCDD …"
         */fingerprint: String, isTrusted: Bool) {
        self.deviceId = deviceId
        self.fingerprint = fingerprint
        self.isTrusted = isTrusted
    }
}

#if compiler(>=6)
extension FfiFingerprint: Sendable {}
#endif


extension FfiFingerprint: Equatable, Hashable {
    public static func ==(lhs: FfiFingerprint, rhs: FfiFingerprint) -> Bool {
        if lhs.deviceId != rhs.deviceId {
            return false
        }
        if lhs.fingerprint != rhs.fingerprint {
            return false
        }
        if lhs.isTrusted != rhs.isTrusted {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(deviceId)
        hasher.combine(fingerprint)
        hasher.combine(isTrusted)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiFingerprint: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiFingerprint {
        return
            try FfiFingerprint(
                deviceId: FfiConverterUInt32.read(from: &buf), 
                fingerprint: FfiConverterString.read(from: &buf), 
                isTrusted: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiFingerprint, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.deviceId, into: &buf)
        FfiConverterString.write(value.fingerprint, into: &buf)
        FfiConverterBool.write(value.isTrusted, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFingerprint_lift(_ buf: RustBuffer) throws -> FfiFingerprint {
    return try FfiConverterTypeFfiFingerprint.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiFingerprint_lower(_ value: FfiFingerprint) -> RustBuffer {
    return FfiConverterTypeFfiFingerprint.lower(value)
}


/**
 * A chat message as seen by the iOS UI.
 */
public struct FfiMessage {
    public var id: String
    public var fromJid: String
    public var toJid: String
    public var body: String
    /**
     * Unix timestamp (seconds since epoch)
     */
    public var timestamp: Int64
    public var isEncrypted: Bool
    /**
     * "sent" | "delivered" | "read" | "failed"
     */
    public var status: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, fromJid: String, toJid: String, body: String, 
        /**
         * Unix timestamp (seconds since epoch)
         */timestamp: Int64, isEncrypted: Bool, 
        /**
         * "sent" | "delivered" | "read" | "failed"
         */status: String) {
        self.id = id
        self.fromJid = fromJid
        self.toJid = toJid
        self.body = body
        self.timestamp = timestamp
        self.isEncrypted = isEncrypted
        self.status = status
    }
}

#if compiler(>=6)
extension FfiMessage: Sendable {}
#endif


extension FfiMessage: Equatable, Hashable {
    public static func ==(lhs: FfiMessage, rhs: FfiMessage) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.fromJid != rhs.fromJid {
            return false
        }
        if lhs.toJid != rhs.toJid {
            return false
        }
        if lhs.body != rhs.body {
            return false
        }
        if lhs.timestamp != rhs.timestamp {
            return false
        }
        if lhs.isEncrypted != rhs.isEncrypted {
            return false
        }
        if lhs.status != rhs.status {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(fromJid)
        hasher.combine(toJid)
        hasher.combine(body)
        hasher.combine(timestamp)
        hasher.combine(isEncrypted)
        hasher.combine(status)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMessage {
        return
            try FfiMessage(
                id: FfiConverterString.read(from: &buf), 
                fromJid: FfiConverterString.read(from: &buf), 
                toJid: FfiConverterString.read(from: &buf), 
                body: FfiConverterString.read(from: &buf), 
                timestamp: FfiConverterInt64.read(from: &buf), 
                isEncrypted: FfiConverterBool.read(from: &buf), 
                status: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMessage, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.fromJid, into: &buf)
        FfiConverterString.write(value.toJid, into: &buf)
        FfiConverterString.write(value.body, into: &buf)
        FfiConverterInt64.write(value.timestamp, into: &buf)
        FfiConverterBool.write(value.isEncrypted, into: &buf)
        FfiConverterString.write(value.status, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMessage_lift(_ buf: RustBuffer) throws -> FfiMessage {
    return try FfiConverterTypeFfiMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMessage_lower(_ value: FfiMessage) -> RustBuffer {
    return FfiConverterTypeFfiMessage.lower(value)
}


public enum FfiError: Swift.Error {

    
    
    case NotConnected
    case Connection(reason: String
    )
    case Omemo(reason: String
    )
    case Send(reason: String
    )
    case Roster(reason: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NotConnected
        case 2: return .Connection(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 3: return .Omemo(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 4: return .Send(
            reason: try FfiConverterString.read(from: &buf)
            )
        case 5: return .Roster(
            reason: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NotConnected:
            writeInt(&buf, Int32(1))
        
        
        case let .Connection(reason):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Omemo(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Send(reason):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .Roster(reason):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(reason, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lift(_ buf: RustBuffer) throws -> FfiError {
    return try FfiConverterTypeFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiError_lower(_ value: FfiError) -> RustBuffer {
    return FfiConverterTypeFfiError.lower(value)
}


extension FfiError: Equatable, Hashable {}




extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Events the Swift layer receives via `nextEvent()`.
 */

public enum FfiEvent {
    
    /**
     * A new message arrived (or an outgoing message was echoed back).
     */
    case message(msg: FfiMessage
    )
    /**
     * A contact's presence changed.
     */
    case contactUpdate(contact: FfiContact
    )
    /**
     * The connection was lost.
     */
    case disconnected(reason: String
    )
    /**
     * The delivery status of a previously sent message changed.
     */
    case statusUpdate(msgId: String, status: String
    )
    /**
     * A contact started or stopped composing a message.
     * `is_typing` = true → composing; false → paused/inactive/gone.
     */
    case typingUpdate(jid: String, isTyping: Bool
    )
}


#if compiler(>=6)
extension FfiEvent: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEvent: FfiConverterRustBuffer {
    typealias SwiftType = FfiEvent

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEvent {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .message(msg: try FfiConverterTypeFfiMessage.read(from: &buf)
        )
        
        case 2: return .contactUpdate(contact: try FfiConverterTypeFfiContact.read(from: &buf)
        )
        
        case 3: return .disconnected(reason: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .statusUpdate(msgId: try FfiConverterString.read(from: &buf), status: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .typingUpdate(jid: try FfiConverterString.read(from: &buf), isTyping: try FfiConverterBool.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiEvent, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .message(msg):
            writeInt(&buf, Int32(1))
            FfiConverterTypeFfiMessage.write(msg, into: &buf)
            
        
        case let .contactUpdate(contact):
            writeInt(&buf, Int32(2))
            FfiConverterTypeFfiContact.write(contact, into: &buf)
            
        
        case let .disconnected(reason):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(reason, into: &buf)
            
        
        case let .statusUpdate(msgId,status):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(msgId, into: &buf)
            FfiConverterString.write(status, into: &buf)
            
        
        case let .typingUpdate(jid,isTyping):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(jid, into: &buf)
            FfiConverterBool.write(isTyping, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEvent_lift(_ buf: RustBuffer) throws -> FfiEvent {
    return try FfiConverterTypeFfiEvent.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEvent_lower(_ value: FfiEvent) -> RustBuffer {
    return FfiConverterTypeFfiEvent.lower(value)
}


extension FfiEvent: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiEvent: FfiConverterRustBuffer {
    typealias SwiftType = FfiEvent?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiEvent.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiEvent.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiContact: FfiConverterRustBuffer {
    typealias SwiftType = [FfiContact]

    public static func write(_ value: [FfiContact], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiContact.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiContact] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiContact]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiContact.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiFingerprint: FfiConverterRustBuffer {
    typealias SwiftType = [FfiFingerprint]

    public static func write(_ value: [FfiFingerprint], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiFingerprint.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiFingerprint] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiFingerprint]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiFingerprint.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiMessage: FfiConverterRustBuffer {
    typealias SwiftType = [FfiMessage]

    public static func write(_ value: [FfiMessage], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiMessage.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiMessage] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiMessage]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiMessage.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureChatterboxInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * Return all buffered log lines as a single newline-separated string.
 * Call from Swift to get the full in-session log for export.
 */
public func getLogContents() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_chatterbox_fn_func_get_log_contents($0
    )
})
}
/**
 * Open (and truncate) the persistent log file at `path`.  Call this once at
 * app startup, before `connect()`.  All subsequent log lines will be written
 * to that file AND to the in-memory buffer.  Any lines already in the buffer
 * are flushed to the file first so no early logs are lost.
 *
 * The file is kept open for the lifetime of the process so every log line
 * reaches disk even if the app is killed, unlike an in-memory buffer.
 */
public func setLogFile(path: String)  {try! rustCall() {
    uniffi_chatterbox_fn_func_set_log_file(
        FfiConverterString.lower(path),$0
    )
}
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_chatterbox_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_chatterbox_checksum_func_get_log_contents() != 53127) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_func_set_log_file() != 64639) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_connect() != 40716) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_delete_conversation() != 23155) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_disconnect() != 14714) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_distrust_device() != 32923) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_fetch_mam() != 13931) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_get_contacts() != 31375) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_get_fingerprints() != 51149) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_list_conversations() != 63186) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_load_history() != 6830) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_next_event() != 18508) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_send_message() != 12952) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_send_typing() != 32670) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_method_chatterboxclient_trust_device() != 48370) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_chatterbox_checksum_constructor_chatterboxclient_new() != 51383) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureChatterboxInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all